### ISSUE TITLE
DNS von vpn4 (10.116.152.1) noch im gateway.pp eingetragen

### ISSUE THREAD

**Issue by fsteinel** [freifunk-kiel/ffki-puppet-gateway-install#1]
Es steht noch der DNS des vpn4 im gateway.pp

**Comment by rubo77** [comment]
Laufen denn die DNS auf von 5 und 6 schon korrekt? daB müssten wir die auch NAL alle ein pflegen

**Comment by fsteinel** [comment]
Ja, DNS auf 5 und 6 haben die aktuelle soa
Ich habe auch auf den vorletzten commit per 

``` sh
echo ffki;for DNS in {0..6}; do echo -n "vpn${DNS}: ";dig @vpn${DNS}.ffki ns6.ffki +short A ; done;
```

 geprüft

**Comment by rubo77** [comment]
Ist das fertig?
